name: terraform-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  PushToAWS:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies and build React app
        run: |
          cd Landing-page-react
          npm install
          npm run build

      - name: Archive production artifacts
        run: |
          cd Landing-page-react
          zip -r react_build.zip build

      - name: Push React build to S3
        uses: jakejarvis/s3-sync-action@v0.3.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'Landing-page-react/build'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform fmt && terraform init -upgrade

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_lb_subnets: '["subnet-12345678","subnet-87654321"]'  # Ensure these are in different AZs
